from .SSIM import SSIM
from .MS_SSIM import MS_SSIM
from .CW_SSIM import CW_SSIM
from .GMSD import GMSD
from .NLPD import NLPD
from .FSIM import FSIM
from .VSI import VSI
from .VIF import VIF
from .VIFs import VIFs
from .MAD import MAD
from .LPIPSvgg import LPIPSvgg
from .DISTS import DISTS